### ISSUE TITLE
Data_prep.py Error

### ISSUE THREAD

**Issue by adeelnasrullah** [IdahoLabResearch/5GAD#2]
I am trying to run the Data_prep.py file on my PC, and I see the following issue:

Start processing normal-1ue data
This could take up to an hour or more
  0%|                                                     | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/adeelnasrullah/Downloads/5GAD-main/Data_prep.py", line 40, in <module>
    pcap = sniff(offline=str(file))
  File "/Users/adeelnasrullah/opt/anaconda3/lib/python3.9/site-packages/scapy/sendrecv.py", line 1263, in sniff
    sniffer._run(*args, **kwargs)
  File "/Users/adeelnasrullah/opt/anaconda3/lib/python3.9/site-packages/scapy/sendrecv.py", line 1072, in _run
    sniff_sockets.update((PcapReader(
  File "/Users/adeelnasrullah/opt/anaconda3/lib/python3.9/site-packages/scapy/sendrecv.py", line 1072, in <genexpr>
    sniff_sockets.update((PcapReader(
  File "/Users/adeelnasrullah/opt/anaconda3/lib/python3.9/site-packages/scapy/utils.py", line 1172, in __call__
    raise Scapy_Exception("Not a supported capture file")
scapy.error.Scapy_Exception: Not a supported capture file

Looks like there is a format issue with pcapng files. Opening these files with wireshark also fails with wrong file format error.
Any help in this would be really appreciated.

**Comment by CooperColdwell** [comment]
The files were created in Ubuntu, so the file extensions were manually appended. Try changing .pcapng to .pcap and see if that makes a difference

**Comment by adeelnasrullah** [comment]
I have tried doing it, but it does not make any difference. I get the same error.

**Comment by adeelnasrullah** [comment]
I was able to open the files. 
There was no issue with the files. I did not realize that I had to fetch data files using git-lfs after git clone.
